apiVersion: v1
kind: ServiceAccount
metadata:
  name: portfolio-workflow-sa
  namespace: argo-workflows
---
apiVersion: v1
kind: Secret
metadata:
  name: portfolio-workflow-sa-token
  namespace: argo-workflows
  annotations:
    kubernetes.io/service-account.name: portfolio-workflow-sa
type: kubernetes.io/service-account-token
